server:
  port: 8081


spring:
  application:
    name: server2

  datasource:
    url: jdbc:postgresql://localhost:5432/deletekafkaserver2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
