
server:
  port: 8080

spring:
  application:
    name: server1

  datasource:
    url: jdbc:postgresql://localhost:5432/deletekafkaserver
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

